name: Build Desktop App with Flet Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet

      - name: Build with Flet
        run: |
          # pomodorotimer.toml に記載された設定に基づいてパッケージ化します。
          flet build ${{ matrix.target }} --include-packages flet_audio

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-timer-app-${{ matrix.target }}
          path: dist/*